[build]
target = "aarch64-unknown-linux-gnu"
# target = "riscv64gc-unknown-linux-gnu"


[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc-14"
rustflags = ["-L", "/usr/lib/gcc-cross/aarch64-linux-gnu/14/"]
